import test from 'node:test';import assert from 'node:assert/strict';import {demoSchool,lessons,questions,chapters} from '../src/content.js';import {newUser,mutate,xpOf,gradeUser,streakOf} from '../src/domain.js';import {makeXlsx} from '../src/export.js';
const setup=()=>({s:demoSchool(),u:newUser('u','Học sinh','demo-class'),t:newUser('t','Giáo viên','','teacher')});
test('all lessons and question references valid',()=>{assert.equal(lessons.length,51);assert.equal(new Set(questions.map(x=>x.id)).size,51);for(const l of lessons){assert.equal(l.concepts.length,4);assert.equal(l.question.options.length,4);assert.ok(l.question.correct>=0&&l.question.correct<4)}});
test('completion is idempotent and cannot award arbitrary XP',()=>{let {s,u}=setup();u=mutate(s,u,'complete',{id:'kntt-9-1',xp:999999}).user;u=mutate(s,u,'complete',{id:'kntt-9-1'}).user;assert.equal(xpOf(u),20);assert.equal(u.progress.completed.length,1)});
test('students cannot modify classes or grade submissions',()=>{const {s,u}=setup();assert.throws(()=>mutate(s,u,'saveEntity',{collection:'classes',entity:{id:'x',name:'X',code:'XXXX'}}));assert.throws(()=>gradeUser(u,u,{id:'x',score:10}))});
test('assignment ownership and immutable submission',()=>{const {s,u}=setup();assert.throws(()=>mutate(s,{...u,classId:'wrong'},'submitAssignment',{id:'assignment-demo',text:'Bài làm'}));const v=mutate(s,u,'submitAssignment',{id:'assignment-demo',text:'Bài làm'}).user;assert.equal(v.submissions[0].score,null);assert.throws(()=>mutate(s,v,'submitAssignment',{id:'assignment-demo',text:'Ghi đè'}))});
test('exam score computed from snapshot and teacher essay grade',()=>{let {s,u,t}=setup();u=mutate(s,u,'startExam',{id:'exam-demo',attemptId:'a'},1000).user;const answers=Object.fromEntries(questions.slice(0,10).map(q=>[q.id,q.correct]));u=mutate(s,u,'submitExam',{id:'a',answers,essay:'Báo giáo viên khi có sự cố.',score:10},2000).user;assert.equal(u.attempts[0].autoScore,8);assert.equal(u.attempts[0].score,null);u=gradeUser(t,u,{type:'exam',id:'a',score:1.5,feedback:'Khá tốt'});assert.equal(u.attempts[0].score,9.5);assert.throws(()=>mutate(s,u,'submitExam',{id:'a'}))});
test('deadline rejects late answer changes and uses saved answers',()=>{let {s,u}=setup();u=mutate(s,u,'startExam',{id:'exam-demo',attemptId:'a'},1000).user;u=mutate(s,u,'saveExam',{id:'a',answers:{'kntt9-q-1':0}},2000).user;u=mutate(s,u,'submitExam',{id:'a',answers:{'kntt9-q-1':2,'kntt9-q-2':1}},1000000).user;assert.deepEqual(u.attempts[0].answers,{'kntt9-q-1':0});assert.equal(u.attempts[0].autoScore,.8)});
test('third proctor violation submits and attempt limit enforced',()=>{let {s,u}=setup();s.exams[0].proctor=true;s.exams[0].maxAttempts=1;u=mutate(s,u,'startExam',{id:'exam-demo',attemptId:'a'},1000).user;for(let i=0;i<3;i++)u=mutate(s,u,'violation',{id:'a'},2000+i).user;assert.equal(u.attempts[0].status,'pending');assert.throws(()=>mutate(s,u,'startExam',{id:'exam-demo',attemptId:'b'},3000))});
test('game rewards verified and deduplicated',()=>{let {s,u}=setup();const answers=questions.slice(0,5).map(q=>({id:q.id,value:q.correct}));u=mutate(s,u,'gameWin',{id:'brain',answers}).user;u=mutate(s,u,'gameWin',{id:'brain',answers}).user;assert.equal(xpOf(u),25);assert.throws(()=>mutate(s,u,'gameWin',{id:'fake',answers}))});
test('duplicate join codes prevented and invalid references rejected',()=>{const {s,t}=setup();assert.throws(()=>mutate(s,t,'saveEntity',{collection:'classes',entity:{id:'new',name:'6B',code:'KHTN9DEMO'}}));assert.throws(()=>mutate(s,t,'saveEntity',{collection:'exams',entity:{...s.exams[0],id:'x',questionIds:['missing']}}))});
test('streak uses Vietnam calendar dates',()=>{const {u}=setup();u.progress.activeDates=['2026-09-11','2026-09-12'];assert.equal(streakOf(u,new Date('2026-09-12T10:00:00Z')),2)});
test('xlsx has ZIP signature and escapes string formulas',async()=>{const b=makeXlsx([['Họ tên','Điểm'],['=1+1',9.5]]);const bytes=new Uint8Array(await b.arrayBuffer());assert.equal(bytes[0],80);assert.equal(bytes[1],75);const txt=new TextDecoder().decode(bytes);assert.ok(txt.includes('t="inlineStr"'));assert.ok(txt.includes('<v>9.5</v>'));assert.ok(!txt.includes('<f>'))});
import {validateAccount,changeRole} from '../src/accounts.js';
test('account provisioning validates role and never persists password',()=>{const {s,u,t}=setup();const p={id:'new',name:'An',username:'an.6a',password:'safe-demo-123',classId:'demo-class'};assert.throws(()=>validateAccount(u,s,p));const value=validateAccount(t,s,p);assert.equal(value.email,'an.6a@students.khtn9.local');assert.equal(value.password,undefined);assert.throws(()=>validateAccount(t,s,{...p,classId:'missing'}))});
test('only principal administrator can grant teacher role',()=>{const {u,t}=setup();assert.throws(()=>changeRole(t,u,'teacher'));assert.equal(changeRole({...t,isAdmin:true},u,'teacher').role,'teacher');assert.throws(()=>changeRole({...t,isAdmin:true},t,'student'))});
test('AI settings enforce model format and byte cap',()=>{const {s,u,t}=setup();assert.throws(()=>mutate(s,u,'aiSettings',{models:'gemini-2.5-flash',knowledge:''}));assert.throws(()=>mutate(s,t,'aiSettings',{models:'../../bad',knowledge:''}));assert.throws(()=>mutate(s,t,'aiSettings',{models:'gemini-2.5-flash',knowledge:'a'.repeat(30001)}));assert.equal(mutate(s,t,'aiSettings',{models:'gemini-2.5-flash',knowledge:'Khoa học'}).school.settings.knowledge,'Khoa học')});

test("KNTT curriculum covers 51 ordered lessons in 14 chapters and introduction without broken references",()=>{assert.equal(chapters.length,15);assert.deepEqual(lessons.map(l=>l.number),Array.from({length:51},(_,i)=>i+1));for(const l of lessons){const c=chapters.find(c=>c.id===l.chapter);assert.ok(l.number>=c.start&&l.number<=c.end);assert.equal(l.question.lessonId,l.id);assert.ok(l.hook&&l.activity&&l.question.explanation);assert.equal(new Set(l.question.options).size,4)}assert.equal(lessons[50].title,"Bài 51. Sự phát sinh và phát triển sự sống trên Trái Đất");});
