// Only imported by Vercel functions. Never bundle a service key into the client.
export const config=()=>({url:process.env.SUPABASE_URL?.replace(/\/$/,''),key:process.env.SUPABASE_ANON_KEY,secret:process.env.SUPABASE_SERVICE_ROLE_KEY});
export const configured=()=>{const c=config();return !!(c.url?.startsWith('https://')&&c.key&&c.secret)};
export async function request(path,{method='GET',body,bearer,publicKey=false}={}){const c=config();const key=publicKey?c.key:c.secret;const r=await fetch(c.url+path,{method,headers:{apikey:key,...(bearer||!key?.startsWith('sb_')?{Authorization:'Bearer '+(bearer||key)}:{}),'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(15000)});const j=await r.json().catch(()=>null);if(!r.ok){const conflict=r.status===409||j?.code==='40001';const error=Object.assign(Error(conflict?'Dữ liệu vừa thay đổi. Hãy làm mới và thử lại.':r.status===401?'Phiên đăng nhập hết hạn.':r.status===429?'Thao tác quá nhanh. Vui lòng chờ một chút.':'Không kết nối được Supabase hoặc chưa cài cơ sở dữ liệu.'),{status:conflict?409:r.status>=500?503:r.status});throw error}return j}
export async function identity(bearer){const j=await request('/auth/v1/user',{bearer,publicKey:true});if(!j?.id)throw Object.assign(Error('Cần đăng nhập.'),{status:401});return {localId:j.id,email:j.email,displayName:j.user_metadata?.display_name,emailVerified:!!j.email_confirmed_at}}
export async function read(path){const rows=await request('/rest/v1/khtn9_records?record_key=eq.'+encodeURIComponent(path)+'&select=payload,version');const r=rows?.[0];return r?{value:r.payload,version:r.version}:null}
export async function commit(changes){return request('/rest/v1/rpc/khtn9_commit',{method:'POST',body:{changes:changes.map(x=>({key:x.path,payload:x.value,expected_version:x.old?.version??0}))}})}
export async function allUsers(){let out=[],offset=0;for(;;){const rows=await request('/rest/v1/khtn9_records?record_key=like.users%2F*&select=payload&order=record_key&limit=200&offset='+offset);out.push(...rows.map(r=>r.payload));if(rows.length<200)return out;offset+=200}}
export async function createAccount(value,password){const j=await request('/auth/v1/admin/users',{method:'POST',body:{email:value.email,password,email_confirm:true,user_metadata:{display_name:value.name}}});return {...value,id:j.id}}
export async function resetPassword(id,password){await request('/auth/v1/admin/users/'+encodeURIComponent(id),{method:'PUT',body:{password}})}
