import {periodsOf,validatePeriods,learningAction} from './learning.js';
import {games} from './content.js';
export const dayKey=(date=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
export function newUser(id,name,classId='',role='student'){return {id,name,classId,role,progress:{completed:[],studySeconds:0,activeDates:[],gameWins:[]},attempts:[],submissions:[]}}
export function xpOf(u){return u.progress.completed.length*20+u.progress.gameWins.length*25}
export function streakOf(u,now=new Date()){const dates=new Set(u.progress.activeDates);let n=0;let d=new Date(now);if(!dates.has(dayKey(d)))d=new Date(+d-86400000);while(dates.has(dayKey(d))){n++;d=new Date(+d-86400000)}return n}
const insist=(test,message)=>{if(!test)throw new Error(message)};
const str=(x,max=200)=>{insist(typeof x==='string'&&x.trim().length>0&&x.length<=max,'Nội dung trống hoặc quá dài.');return x.trim()};
export function mutate(school,user,action,p={},now=Date.now()){
const s=structuredClone(school),u=structuredClone(user);const teacher=u.role==='teacher';
const active=()=>{const d=dayKey(new Date(now));if(!u.progress.activeDates.includes(d))u.progress.activeDates.push(d)};
if(['periodQuiz','periodComplete','periodStudy'].includes(action)){learningAction(s,u,action,p,now);active()}
else if(action==='complete'){const lesson=s.lessons.find(l=>l.id===p.id);insist(lesson,'Không tìm thấy bài học.');insist(periodsOf(lesson).every(t=>u.progress.periods?.[lesson.id+'/'+t.id]?.completed),'Hãy hoàn thành các tiết học trước.');if(!u.progress.completed.includes(p.id))u.progress.completed.push(p.id);active()}
else if(action==='study'){insist(Number.isFinite(p.seconds)&&p.seconds>=0&&p.seconds<=60,'Thời gian không hợp lệ.');u.progress.studySeconds+=p.seconds;active()}
else if(action==='profile'){u.name=str(p.name,80)}
else if(action==='join'){const c=s.classes.find(c=>c.code===String(p.code).trim().toUpperCase());insist(c,'Mã lớp không đúng.');u.classId=c.id}
else if(action==='submitAssignment'){const a=s.assignments.find(a=>a.id===p.id);insist(a&&a.classId===u.classId,'Bài tập không thuộc lớp của em.');insist(!u.submissions.some(x=>x.assignmentId===a.id),'Bài đã nộp; không thể ghi đè.');u.submissions.push({id:p.id,assignmentId:a.id,text:str(p.text,20000),submittedAt:now,late:now>new Date(a.dueDate+'T23:59:59+07:00').getTime(),score:null,feedback:''});active()}
else if(action==='startExam'){const e=s.exams.find(e=>e.id===p.id);insist(e&&e.classId===u.classId,'Đề không thuộc lớp.');insist(typeof p.attemptId==='string'&&p.attemptId.length<=100&&!u.attempts.some(a=>a.id===p.attemptId),'Mã lượt thi không hợp lệ.');insist(!u.attempts.some(a=>a.status==='active'),'Đã có bài thi đang làm.');insist(u.attempts.filter(a=>a.examId===e.id).length<e.maxAttempts,'Đã hết lượt làm bài.');u.attempts.push({id:p.attemptId,examId:e.id,status:'active',startedAt:now,deadline:now+e.duration*60000,answers:{},essay:'',violations:0,questionIds:[...e.questionIds],questions:e.questionIds.map(id=>s.questions.find(q=>q.id===id)),essayPrompt:e.essay,essayPoints:e.essayPoints||0,proctor:!!e.proctor,category:e.category});}
else if(['saveExam','submitExam','violation'].includes(action)){const a=u.attempts.find(a=>a.id===p.id);insist(a&&a.status==='active','Lượt thi không hoạt động.');if(action==='violation')a.violations++;
if(p.answers&&now<=a.deadline){for(const [id,v]of Object.entries(p.answers)){insist(a.questionIds.includes(id)&&Number.isInteger(v)&&v>=0&&v<4,'Đáp án không hợp lệ.');a.answers[id]=v}if(typeof p.essay==='string')a.essay=p.essay.slice(0,20000)}
if(action==='submitExam'||now>=a.deadline||a.proctor&&a.violations>=3){a.status=a.essayPoints?'pending':'graded';a.submittedAt=now;a.autoScore=Math.round(a.questions.reduce((n,q)=>n+(a.answers[q.id]===q.correct?1:0),0)/a.questions.length*(10-a.essayPoints)*100)/100;a.essayScore=a.essayPoints?null:0;a.score=a.essayPoints?null:a.autoScore;active()}}
else if(action==='gameWin'){insist(games.some(g=>g.id===p.id),'Trò chơi không tồn tại.');insist(Array.isArray(p.answers)&&p.answers.length>=3,'Chưa hoàn thành trò chơi.');const ids=new Set(p.answers.map(a=>a.id));insist(ids.size===p.answers.length,'Câu trả lời trùng.');const correct=p.answers.filter(a=>s.questions.some(q=>q.id===a.id&&q.correct===a.value)).length;insist(correct/p.answers.length>=0.6,'Cần đúng ít nhất 60% để nhận huy hiệu.');if(!u.progress.gameWins.includes(p.id))u.progress.gameWins.push(p.id);active()}
else if(action==='saveEntity'){insist(teacher,'Chỉ giáo viên được thay đổi học liệu.');insist(['classes','lessons','questions','exams','assignments','announcements'].includes(p.collection),'Loại dữ liệu không hợp lệ.');const e=structuredClone(p.entity);e.id=str(e.id,100);if(p.collection==='classes'){e.name=str(e.name,80);e.code=str(e.code,30).toUpperCase();insist(/^[A-Z0-9-]{4,30}$/.test(e.code),'Mã lớp cần 4–30 chữ/số không dấu.');insist(!s.classes.some(c=>c.id!==e.id&&c.code===e.code),'Mã lớp đã tồn tại.')}
if(['lessons','exams','assignments','announcements'].includes(p.collection))e.title=str(e.title,200);
if(['exams','assignments','announcements'].includes(p.collection))insist(s.classes.some(c=>c.id===e.classId),'Chọn lớp hợp lệ.');
if(p.collection==='lessons'){insist(Array.isArray(e.concepts)&&e.concepts.length>0,'Cần kiến thức chính.');e.concepts=e.concepts.map(x=>str(x,5000));e.hook=str(e.hook,2000);e.activity=str(e.activity,5000);insist(Number.isInteger(e.chapter)&&e.chapter>=0&&e.chapter<=14,'Chọn chương hợp lệ.');insist(Number.isInteger(e.minutes)&&e.minutes>=1&&e.minutes<=180,'Thời lượng không hợp lệ.');if(e.periods)validatePeriods(e,s)}
if(p.collection==='questions'){e.text=str(e.text,2000);insist(Array.isArray(e.options)&&e.options.length===4,'Cần đúng 4 phương án.');e.options=e.options.map(x=>str(x,1000));insist(Number.isInteger(e.correct)&&e.correct>=0&&e.correct<4,'Chọn đáp án đúng.');e.explanation=str(e.explanation,3000)}
if(p.collection==='exams'){insist(Number.isInteger(e.duration)&&e.duration>=1&&e.duration<=180,'Thời lượng từ 1 đến 180 phút.');insist(Number.isInteger(e.maxAttempts)&&e.maxAttempts>=1&&e.maxAttempts<=10,'Số lượt từ 1 đến 10.');insist(Array.isArray(e.questionIds)&&e.questionIds.length>0&&new Set(e.questionIds).size===e.questionIds.length&&e.questionIds.every(id=>s.questions.some(q=>q.id===id)),'Danh sách câu hỏi không hợp lệ.');insist(Number.isFinite(e.essayPoints)&&e.essayPoints>=0&&e.essayPoints<=9,'Điểm tự luận từ 0 đến 9.');insist(!e.essayPoints||e.essay?.trim(),'Cần câu hỏi tự luận.');insist(['ĐTX','ĐGK','ĐCK'].includes(e.category),'Loại điểm không hợp lệ.')}
if(p.collection==='assignments'){e.description=str(e.description,10000);insist(/^\d{4}-\d{2}-\d{2}$/.test(e.dueDate)&&Number.isFinite(Date.parse(e.dueDate)),'Hạn nộp không hợp lệ.')}
if(p.collection==='announcements')e.body=str(e.body,5000);
const idx=s[p.collection].findIndex(x=>x.id===e.id);if(idx<0)s[p.collection].push(e);else s[p.collection][idx]=e;}
else if(action==='aiSettings'){insist(teacher,'Chỉ giáo viên được cài đặt AI.');insist(typeof p.models==='string'&&p.models.length<=300&&p.models.split(',').every(x=>/^[a-zA-Z0-9.-]+$/.test(x.trim())),'Danh sách model không hợp lệ.');insist(typeof p.knowledge==='string'&&new TextEncoder().encode(p.knowledge).length<=30000,'Kho kiến thức tối đa 30 KB.');s.settings.aiModels=p.models;s.settings.knowledge=p.knowledge}
else if(action==='settings'){insist(teacher,'Chỉ giáo viên được cài đặt.');s.settings.schoolName=str(p.schoolName,150);s.settings.year=str(p.year,30)}
else throw new Error('Thao tác không được hỗ trợ.');
return {school:s,user:u};}
export function gradeUser(actor,target,p){insist(actor.role==='teacher','Chỉ giáo viên được chấm bài.');const u=structuredClone(target);const row=p.type==='exam'?u.attempts.find(x=>x.id===p.id):u.submissions.find(x=>x.id===p.id);insist(row,'Không tìm thấy bài nộp.');insist(p.type!=='exam'||row.status!=='active','Bài thi chưa nộp.');const max=p.type==='exam'?row.essayPoints:10;insist(Number.isFinite(p.score)&&p.score>=0&&p.score<=max,'Điểm vượt giới hạn.');if(p.type==='exam'){row.essayScore=p.score;row.score=Math.round((row.autoScore+p.score)*100)/100;row.status='graded'}else row.score=p.score;row.feedback=String(p.feedback||'').slice(0,5000);return u}
