import React,{useEffect,useRef,useState} from 'react';
import {Clock,ShieldCheck,Send,ArrowLeft,CheckCircle2} from 'lucide-react';
import {useApp} from './store.jsx';
export default function Exam({id,go}){const a=useApp(),e=a.school.exams.find(e=>e.id===id);const active=a.user.attempts.find(x=>x.examId===id&&x.status==='active');const attempts=a.user.attempts.filter(x=>x.examId===id);const [answers,A]=useState({}),[essay,E]=useState(''),[now,N]=useState(Date.now()),[confirm,C]=useState(false),[saved,S]=useState(''),[posting,P]=useState(false);const latest=useRef({answers,essay});latest.current={answers,essay};const activeRef=useRef(active);activeRef.current=active;const sending=useRef(false);const lastViolation=useRef(0);
useEffect(()=>{if(active){N(Date.now());A(active.answers);E(active.essay)}},[active?.id]);
async function save(submit=false){const current=activeRef.current;if(!current||sending.current)return;sending.current=true;P(submit);try{await a.act(submit?'submitExam':'saveExam',{id:current.id,...latest.current});S('Đã lưu '+new Date().toLocaleTimeString('vi-VN'));C(false)}catch{S('Chưa lưu được — giữ cửa sổ và thử lại.')}finally{sending.current=false;P(false)}}
useEffect(()=>{if(!active?.id)return;const t=setInterval(()=>{N(Date.now());if(Date.now()>=activeRef.current?.deadline)save(true)},1000);const autosave=setInterval(()=>save(),30000);const unload=ev=>{ev.preventDefault();ev.returnValue=''};window.addEventListener('beforeunload',unload);return()=>{clearInterval(t);clearInterval(autosave);window.removeEventListener('beforeunload',unload)}},[active?.id]);
useEffect(()=>{if(!active?.id)return;const t=setTimeout(()=>save(),700);return()=>clearTimeout(t)},[answers,essay]);
useEffect(()=>{if(!active?.proctor)return;const violation=()=>{if(!activeRef.current||Date.now()-lastViolation.current<1500)return;lastViolation.current=Date.now();a.act('violation',{id:activeRef.current.id,...latest.current}).catch(()=>{})};const visibility=()=>{if(document.hidden)violation()};const full=()=>{if(!document.fullscreenElement)violation()};document.addEventListener('visibilitychange',visibility);document.addEventListener('fullscreenchange',full);return()=>{document.removeEventListener('visibilitychange',visibility);document.removeEventListener('fullscreenchange',full)}},[active?.id]);
if(!e)return <div className="empty">Không tìm thấy đề kiểm tra.</div>;
if(!active)return <div className="exam-start panel"><span className="icon-box teal"><ShieldCheck size={30}/></span><h1>{e.title}</h1><p>{e.duration} phút · {e.questionIds.length} câu trắc nghiệm {e.essay?'và tự luận':''} · {e.maxAttempts} lượt tối đa</p><div className="notice">Bài làm được lưu sau khi đổi đáp án và định kỳ 30 giây. Khi hết giờ, hệ thống nộp các đáp án đã lưu. {e.proctor?'Bài này yêu cầu toàn màn hình; 3 lần rời màn hình sẽ tự nộp. Đây là tín hiệu giám sát, không phải bằng chứng kết luận gian lận.':'Hãy tập trung và tự làm bài bằng kiến thức của em.'}</div><button className="primary" disabled={a.busy||attempts.length>=e.maxAttempts} onClick={async()=>{if(e.proctor){try{if(!document.documentElement.requestFullscreen)throw Error();await document.documentElement.requestFullscreen()}catch{a.setError('Thiết bị không hỗ trợ toàn màn hình. Hãy dùng máy tính hoặc nhờ giáo viên đổi cấu hình đề.');return}}await a.act('startExam',{id,attemptId:crypto.randomUUID()}).catch(()=>{})}}>Bắt đầu làm bài</button><button className="text-btn" onClick={()=>go('/app/exams')}>← Danh sách đề</button>{attempts.map((x,i)=><div className="result panel" key={x.id}><h3>Lượt {i+1} · {x.status==='pending'?'Chờ giáo viên chấm tự luận':'Đã chấm'}</h3><b>Trắc nghiệm: {x.autoScore}/{10-x.essayPoints}</b><p>Tổng điểm: {x.score===null?'Chờ chấm':x.score+'/10'}</p>{x.feedback&&<p>Nhận xét: {x.feedback}</p>}<p>Số lần rời màn hình: {x.violations}</p></div>)}</div>;
const seconds=Math.max(0,Math.ceil((active.deadline-now)/1000));return <div className="exam-room" onCopy={ev=>active.proctor&&ev.preventDefault()} onPaste={ev=>active.proctor&&ev.preventDefault()}><div className="exam-top"><div><span className="eyebrow">BÀI KIỂM TRA ĐANG DIỄN RA</span><h1>{e.title}</h1><small role="status">{saved||'Đang làm bài'} {active.proctor?'· Rời màn hình: '+active.violations+'/3':''}</small></div><span className={'timer '+(seconds<60?'urgent':'')}><Clock/>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span></div><div className="exam-layout"><div>{active.questions.map((q,i)=><section className="panel" id={'question-'+i} key={q.id}><span className="eyebrow">CÂU {i+1}</span><h3>{q.text}</h3><div className="options">{q.options.map((o,n)=><button className={answers[q.id]===n?'chosen':''} key={n} onClick={()=>A(prev=>({...prev,[q.id]:n}))}><span>{'ABCD'[n]}</span>{o}</button>)}</div></section>)}{active.essayPoints>0&&<section className="panel"><h3>Tự luận · {active.essayPoints} điểm</h3><p>{active.essayPrompt}</p><textarea aria-label="Bài làm tự luận" value={essay} onChange={ev=>E(ev.target.value)} rows={9} maxLength={20000}/></section>}</div><div className="exam-summary panel"><h3>Phiếu trả lời</h3><p>{Object.keys(answers).length}/{active.questions.length} câu đã chọn</p><div className="question-map">{active.questions.map((q,i)=><button key={q.id} className={answers[q.id]!==undefined?'answered':''} onClick={()=>document.getElementById('question-'+i)?.scrollIntoView({behavior:'smooth'})}>{i+1}</button>)}</div><button className="secondary wide" disabled={a.busy} onClick={()=>save()}>Lưu bài ngay</button><button className="primary wide" onClick={()=>C(true)} disabled={posting}>Nộp bài<Send size={16}/></button></div></div>{confirm&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="submit-title"><h2 id="submit-title">Em đã sẵn sàng nộp bài?</h2><p>Còn {active.questions.length-Object.keys(answers).length} câu trắc nghiệm chưa chọn. Sau khi nộp, em không thể sửa lượt này.</p><div className="actions"><button className="secondary" onClick={()=>C(false)}>Kiểm tra lại</button><button className="primary" disabled={posting} onClick={()=>save(true)}>{posting?'Đang nộp…':'Xác nhận nộp'}</button></div></div></div>}</div>}
