// Shared lesson/period rules. Executed by both the demo and the API.
export const mediaTypes=['none','video','slides','document','web'];
export function safeUrl(value){if(!value)return '';try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:''}catch{return ''}}
export function mediaSource(value){const url=safeUrl(value);if(!url)return null;const u=new URL(url);const host=u.hostname.replace(/^www\./,'');let id;if(host==='youtu.be')id=u.pathname.slice(1);if(host==='youtube.com'||host==='m.youtube.com')id=u.searchParams.get('v')||u.pathname.split('/').filter(Boolean)[1];if(id&&/^[\w-]{11}$/.test(id))return {kind:'frame',url:'https://www.youtube-nocookie.com/embed/'+id};if(host==='vimeo.com'&&/^\/\d+$/.test(u.pathname))return {kind:'frame',url:'https://player.vimeo.com/video'+u.pathname};if(/\.(mp4|webm)$/i.test(u.pathname))return {kind:'video',url};return {kind:'frame',url}}
export function periodsOf(l){return l.periods?.length?[...l.periods].sort((a,b)=>a.order-b.order):[{id:l.id+'-core',title:'Khám phá kiến thức & vận dụng',order:1,minutes:l.minutes||20,unlocked:true,html:'',media:{type:'none',url:''},attachments:[],quiz:{enabled:!!l.question,questionIds:l.question?[l.question.id]:[],passScore:5,maxAttempts:0,required:!!l.question}}]}
export function periodQuestions(s,l,p){return p.quiz.questionIds.map(id=>s.questions.find(q=>q.id===id)|| (l.question?.id===id?l.question:null)).filter(Boolean)}
export function periodRecord(u,l,p){return u.progress.periods?.[l.id+'/'+p.id]||{attempts:[],completed:false,seconds:0}}
export function validatePeriods(l,s){if(!Array.isArray(l.periods)||!l.periods.length||l.periods.length>30)throw Error('Mỗi bài cần 1–30 tiết học.');const ids=new Set(),orders=new Set();for(const p of l.periods){if(typeof p.id!=='string'||!p.id||p.id.length>120||ids.has(p.id))throw Error('Mã tiết học trùng hoặc không hợp lệ.');ids.add(p.id);if(!p.title?.trim()||p.title.length>200)throw Error('Tiêu đề tiết học cần 1–200 ký tự.');if(!Number.isInteger(p.order)||p.order<1||orders.has(p.order))throw Error('Thứ tự tiết phải là số nguyên dương, không trùng.');orders.add(p.order);if(!Number.isInteger(p.minutes)||p.minutes<1||p.minutes>180)throw Error('Thời lượng tiết từ 1–180 phút.');if(typeof p.unlocked!=='boolean')throw Error('Quyền truy cập không hợp lệ.');if(typeof p.html!=='string'||p.html.length>80000)throw Error('Nội dung một tiết tối đa 80.000 ký tự.');if(!mediaTypes.includes(p.media?.type)||p.media.type!=='none'&&!safeUrl(p.media.url))throw Error('Media cần liên kết HTTPS hợp lệ.');if(!Array.isArray(p.attachments)||p.attachments.length>10||p.attachments.some(x=>!x.title?.trim()||x.title.length>150||!safeUrl(x.url)||!mediaTypes.includes(x.type)||x.type==='none'))throw Error('Tối đa 10 tài liệu có tên, loại và liên kết HTTPS.');const q=p.quiz;if(!q||typeof q.enabled!=='boolean'||typeof q.required!=='boolean'||!Number.isFinite(q.passScore)||q.passScore<0||q.passScore>10||!Number.isInteger(q.maxAttempts)||q.maxAttempts<0||q.maxAttempts>20)throw Error('Cấu hình củng cố không hợp lệ.');if(q.required&&!q.enabled)throw Error('Hãy bật củng cố trước khi yêu cầu đạt điểm.');if(!Array.isArray(q.questionIds)||new Set(q.questionIds).size!==q.questionIds.length||q.questionIds.length>50||q.enabled&&(!q.questionIds.length||periodQuestions(s,l,p).length!==q.questionIds.length))throw Error('Chọn 1–50 câu hỏi hợp lệ, không trùng.')}}
export function learningAction(s,u,action,p,now){const l=s.lessons.find(x=>x.id===p.lessonId);if(!l)throw Error('Không tìm thấy bài học.');const periods=periodsOf(l),period=periods.find(x=>x.id===p.periodId);if(!period||!period.unlocked)throw Error('Tiết học đang khoá hoặc không tồn tại.');u.progress.periods??={};const key=l.id+'/'+period.id;const r=u.progress.periods[key]??={attempts:[],completed:false,seconds:0};if(action==='periodQuiz'){if(!period.quiz.enabled)throw Error('Bài củng cố chưa bật.');if(period.quiz.maxAttempts&&r.attempts.length>=period.quiz.maxAttempts)throw Error('Đã hết lượt làm bài củng cố.');const qs=periodQuestions(s,l,period);if(!qs.length||!p.answers||qs.some(q=>!Number.isInteger(p.answers[q.id])||p.answers[q.id]<0||p.answers[q.id]>3))throw Error('Hãy trả lời đầy đủ các câu hỏi.');const score=Math.round(qs.filter(q=>p.answers[q.id]===q.correct).length/qs.length*100)/10;r.attempts.push({score,at:now,answers:Object.fromEntries(qs.map(q=>[q.id,p.answers[q.id]])),feedback:qs.map(q=>({id:q.id,correct:q.correct,explanation:q.explanation}))});}
if(action==='periodComplete'){if(period.quiz.required&&!r.attempts.some(x=>x.score>=period.quiz.passScore))throw Error('Cần đạt điểm củng cố trước khi hoàn thành tiết.');r.completed=true;r.completedAt??=now;if(periods.every(x=>u.progress.periods[l.id+'/'+x.id]?.completed)&&!u.progress.completed.includes(l.id))u.progress.completed.push(l.id)}
if(action==='periodStudy'){if(!Number.isInteger(p.seconds)||p.seconds<0||p.seconds>60)throw Error('Thời gian không hợp lệ.');r.seconds+=p.seconds;u.progress.studySeconds+=p.seconds}
}
