import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {demoSchool,questions as defaultQuestions} from './content.js';
import {lessonQuestionsMap} from './lesson-questions.js';
import {newUser,mutate,gradeUser} from './domain.js';
import {validateAccount,changeRole} from './accounts.js';
const C=createContext(null);const KEY='khtn9-demo-kntt-v2';
const defaultDemoUsers=()=>[newUser('demo-student','Minh Anh','demo-class'),newUser('demo-teacher','Thầy / Cô trải nghiệm','','teacher'),{...newUser('admin-pqd','Thầy Phạm Quốc Đạt','','teacher'),isAdmin:true,email:'phamquocdat1991@gmail.com'}];
const loadDemo=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.school?.schemaVersion===2&&x.users?.length){if(!x.users.some(u=>u.email==='phamquocdat1991@gmail.com'||u.isAdmin)){x.users.push({...newUser('admin-pqd','Thầy Phạm Quốc Đạt','','teacher'),isAdmin:true,email:'phamquocdat1991@gmail.com'});}if(!Array.isArray(x.school.questions)||x.school.questions.length<510){const map=new Map((x.school.questions||[]).map(q=>[q.id,q]));for(const q of defaultQuestions){if(!map.has(q.id))map.set(q.id,q);}x.school.questions=Array.from(map.values());}for(const l of x.school.lessons){if(!l.questions||l.questions.length<10){l.questions=lessonQuestionsMap[l.id]||defaultQuestions.filter(q=>q.lessonId===l.id);}}return x;}}catch{}return {school:demoSchool(),users:defaultDemoUsers()}};
export const useApp=()=>useContext(C);
export function Provider({children}){const [config,setConfig]=useState(null),[state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const ref=useRef(state);ref.current=state;const queue=useRef(Promise.resolve());
async function remote(action,payload={}){let session=JSON.parse(sessionStorage.getItem('khtn9-session')||'null');if(!session)throw Error('Cần đăng nhập.');if(session.provider!=='supabase')throw Error('Hệ thống đã chuyển sang Supabase. Vui lòng đăng nhập lại.');if(session.expires<Date.now()){const r=await fetch(config.url+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{'content-type':'application/json',apikey:config.apiKey},body:JSON.stringify({refresh_token:session.refresh})});const j=await r.json();if(!r.ok)throw Error('Phiên hết hạn, vui lòng đăng nhập lại.');session={provider:'supabase',token:j.access_token,refresh:j.refresh_token,expires:Date.now()+(j.expires_in-60)*1000};sessionStorage.setItem('khtn9-session',JSON.stringify(session))}const r=await fetch('/api/lms',{method:'POST',headers:{'content-type':'application/json',Authorization:'Bearer '+session.token},body:JSON.stringify({action,payload}),signal:AbortSignal.timeout(55000)});const j=await r.json();if(!r.ok)throw Error(j.error||'Không kết nối được máy chủ.');return j}
useEffect(()=>{fetch('/api/lms').then(r=>r.json()).then(setConfig).catch(()=>setConfig({configured:false}));},[]);
useEffect(()=>{if(config?.configured&&sessionStorage.getItem('khtn9-session'))remote('state').then(s=>setState({...s,mode:'cloud'})).catch(e=>setError(e.message));else if(config&&sessionStorage.getItem('khtn9-demo-role'))demo(sessionStorage.getItem('khtn9-demo-role'));},[config]);
function demo(role='student'){const d=loadDemo();sessionStorage.setItem('khtn9-demo-role',role);const u=role==='admin'?(d.users.find(x=>x.isAdmin||x.email==='phamquocdat1991@gmail.com')||d.users.find(x=>x.role==='teacher')):d.users.find(x=>x.role===role);setState({...d,user:u,mode:'demo'});setError('')}
function act(action,payload={}){const job=queue.current.catch(()=>{}).then(async()=>{setBusy(true);try{const cur=ref.current;if(!cur)throw Error('Chọn đăng nhập hoặc trải nghiệm.');if(cur.mode==='cloud'){const j=await remote(action,payload);if(action!=='chat'){ref.current={...j,mode:'cloud'};setState(ref.current);}return j}if(action==='chat')throw Error('Trợ lý AI cần tài khoản thật và cấu hình kết nối.');let next;if(action==='createAccount'){const value=validateAccount(cur.user,cur.school,{...payload,id:crypto.randomUUID()});if(cur.users.some(x=>x.email===value.email))throw Error('Tài khoản đã tồn tại.');next={...cur,users:[...cur.users,value]}}else if(action==='resetAccount'){if(cur.user.role!=='teacher'||payload.password?.length<8)throw Error('Không thể cập nhật.');next={...cur}}else if(action==='setRole'){next={...cur,users:cur.users.map(x=>x.id===payload.userId?changeRole({...cur.user,isAdmin:true},x,payload.role):x)}}else if(action==='grade'){const target=cur.users.find(u=>u.id===payload.userId);next={...cur,users:cur.users.map(u=>u.id===payload.userId?gradeUser(cur.user,target,payload):u)}}else{const m=mutate(cur.school,cur.user,action,payload);next={...cur,...m,users:cur.users.map(u=>u.id===m.user.id?m.user:u)}}localStorage.setItem(KEY,JSON.stringify({school:next.school,users:next.users}));ref.current=next;setState(next);return next}catch(e){setError(e.message);throw e}finally{setBusy(false)}});queue.current=job;return job}
async function auth(values,signup){setBusy(true);try{const uName=String(values.username||'').trim().toLowerCase();const pw=String(values.password||'');const isAdmin=(uName==='phamquocdat1991@gmail.com'||uName==='phamquocdat1991')&&pw==='pqdhhvpro1991';if(!config?.configured){if(signup)throw Error('Chưa kết nối Supabase. Tính năng đăng ký tài khoản trực tuyến yêu cầu kết nối đám mây.');if(isAdmin){const d=loadDemo();const adminUser=d.users.find(u=>u.email==='phamquocdat1991@gmail.com'||u.isAdmin)||{...newUser('admin-pqd','Thầy Phạm Quốc Đạt','','teacher'),isAdmin:true,email:'phamquocdat1991@gmail.com'};sessionStorage.setItem('khtn9-demo-role','admin');setState({...d,user:adminUser,mode:'demo'});setError('');return;}if(uName==='phamquocdat1991@gmail.com'||uName==='phamquocdat1991')throw Error('Mật khẩu không chính xác.');if(uName==='demo-teacher'||uName==='giaovien'){demo('teacher');return;}if(uName==='demo-student'||uName==='hocsinh'){demo('student');return;}throw Error('Chưa kết nối Supabase. Bạn có thể đăng nhập bằng tài khoản Admin (phamquocdat1991@gmail.com / pqdhhvpro1991) hoặc dùng chế độ trải nghiệm.');}const name=values.username.includes('@')?values.username:values.username+'@students.khtn9.local';if(signup&&!values.username.includes('@'))throw Error('Đăng ký cần email thật để xác nhận. Tên đăng nhập học sinh do giáo viên cấp.');const r=await fetch(config.url+'/auth/v1/'+(signup?'signup':'token?grant_type=password'),{method:'POST',headers:{'content-type':'application/json',apikey:config.apiKey},body:JSON.stringify({email:name,password:values.password,data:{display_name:values.name}})});const j=await r.json();if(!r.ok)throw Error('Không đăng nhập/đăng ký được. Kiểm tra email, mật khẩu và trạng thái xác nhận email.');if(!j.access_token){setError('Đã gửi yêu cầu đăng ký. Hãy kiểm tra email xác nhận rồi đăng nhập và nhập mã lớp trong Hồ sơ.');return}sessionStorage.setItem('khtn9-session',JSON.stringify({provider:'supabase',token:j.access_token,refresh:j.refresh_token,expires:Date.now()+(j.expires_in-60)*1000}));sessionStorage.removeItem('khtn9-demo-role');let s=await remote('state');if(signup&&values.code)s=await remote('join',{code:values.code});setState({...s,mode:'cloud'});setError('')}catch(e){setError(e.message);throw e}finally{setBusy(false)}}
function logout(){const session=JSON.parse(sessionStorage.getItem('khtn9-session')||'null');if(session?.provider==='supabase'&&config?.url)fetch(config.url+'/auth/v1/logout',{method:'POST',headers:{apikey:config.apiKey,Authorization:'Bearer '+session.token}}).catch(()=>{});sessionStorage.removeItem('khtn9-session');sessionStorage.removeItem('khtn9-demo-role');setState(null)}
return <C.Provider value={{...state,config,error,setError,busy,act,auth,demo,logout,refresh:async()=>{if(state?.mode==='cloud')setState({...await remote('state'),mode:'cloud'})}}}>{children}</C.Provider>}
