import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {demoSchool} from './content.js';
import {newUser,mutate,gradeUser} from './domain.js';
import {validateAccount,changeRole} from './accounts.js';
const C=createContext(null);const KEY='khtn9-demo-kntt-v2';
const loadDemo=()=>{try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.school?.schemaVersion===2&&x.users?.length)return x}catch{}return {school:demoSchool(),users:[newUser('demo-student','Minh Anh','demo-class'),newUser('demo-teacher','Thầy / Cô trải nghiệm','','teacher')]}};
export const useApp=()=>useContext(C);
export function Provider({children}){const [config,setConfig]=useState(null),[state,setState]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const ref=useRef(state);ref.current=state;const queue=useRef(Promise.resolve());
async function remote(action,payload={}){let session=JSON.parse(sessionStorage.getItem('khtn9-session')||'null');if(!session)throw Error('Cần đăng nhập.');if(session.expires<Date.now()){const r=await fetch('https://securetoken.googleapis.com/v1/token?key='+config.apiKey,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:session.refresh})});const j=await r.json();if(!r.ok)throw Error('Phiên hết hạn, vui lòng đăng nhập lại.');session={token:j.id_token,refresh:j.refresh_token,expires:Date.now()+3300000};sessionStorage.setItem('khtn9-session',JSON.stringify(session))}const r=await fetch('/api/lms',{method:'POST',headers:{'content-type':'application/json',Authorization:'Bearer '+session.token},body:JSON.stringify({action,payload}),signal:AbortSignal.timeout(55000)});const j=await r.json();if(!r.ok)throw Error(j.error||'Không kết nối được máy chủ.');return j}
useEffect(()=>{fetch('/api/lms').then(r=>r.json()).then(setConfig).catch(()=>setConfig({configured:false}));},[]);
useEffect(()=>{if(config?.configured&&sessionStorage.getItem('khtn9-session'))remote('state').then(s=>setState({...s,mode:'cloud'})).catch(e=>setError(e.message));else if(config&&sessionStorage.getItem('khtn9-demo-role'))demo(sessionStorage.getItem('khtn9-demo-role'));},[config]);
function demo(role='student'){const d=loadDemo();sessionStorage.setItem('khtn9-demo-role',role);setState({...d,user:d.users.find(u=>u.role===role),mode:'demo'});setError('')}
function act(action,payload={}){const job=queue.current.catch(()=>{}).then(async()=>{setBusy(true);try{const cur=ref.current;if(!cur)throw Error('Chọn đăng nhập hoặc trải nghiệm.');if(cur.mode==='cloud'){const j=await remote(action,payload);if(action!=='chat')setState({...j,mode:'cloud'});return j}if(action==='chat')throw Error('Trợ lý AI cần tài khoản thật và cấu hình kết nối.');let next;if(action==='createAccount'){const value=validateAccount(cur.user,cur.school,{...payload,id:crypto.randomUUID()});if(cur.users.some(x=>x.email===value.email))throw Error('Tài khoản đã tồn tại.');next={...cur,users:[...cur.users,value]}}else if(action==='resetAccount'){if(cur.user.role!=='teacher'||payload.password?.length<8)throw Error('Không thể cập nhật.');next={...cur}}else if(action==='setRole'){next={...cur,users:cur.users.map(x=>x.id===payload.userId?changeRole({...cur.user,isAdmin:true},x,payload.role):x)}}else if(action==='grade'){const target=cur.users.find(u=>u.id===payload.userId);next={...cur,users:cur.users.map(u=>u.id===payload.userId?gradeUser(cur.user,target,payload):u)}}else{const m=mutate(cur.school,cur.user,action,payload);next={...cur,...m,users:cur.users.map(u=>u.id===m.user.id?m.user:u)}}localStorage.setItem(KEY,JSON.stringify({school:next.school,users:next.users}));ref.current=next;setState(next);return next}catch(e){setError(e.message);throw e}finally{setBusy(false)}});queue.current=job;return job}
async function auth(values,signup){setBusy(true);try{if(!config?.configured)throw Error('Chưa kết nối Firebase. Dùng chế độ trải nghiệm để xem app.');const name=values.username.includes('@')?values.username:values.username+'@students.khtn9.local';const r=await fetch('https://identitytoolkit.googleapis.com/v1/accounts:'+(signup?'signUp':'signInWithPassword')+'?key='+config.apiKey,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:name,password:values.password,displayName:values.name,returnSecureToken:true})});const j=await r.json();if(!r.ok)throw Error(j.error?.message==='EMAIL_EXISTS'?'Tài khoản đã tồn tại.':'Không đăng nhập/đăng ký được. Kiểm tra tài khoản, mật khẩu và cấu hình Email/Password.');sessionStorage.setItem('khtn9-session',JSON.stringify({token:j.idToken,refresh:j.refreshToken,expires:Date.now()+3300000}));sessionStorage.removeItem('khtn9-demo-role');let s=await remote('state');if(signup&&values.code)s=await remote('join',{code:values.code});setState({...s,mode:'cloud'});setError('')}catch(e){setError(e.message);throw e}finally{setBusy(false)}}
function logout(){sessionStorage.removeItem('khtn9-session');sessionStorage.removeItem('khtn9-demo-role');setState(null)}
return <C.Provider value={{...state,config,error,setError,busy,act,auth,demo,logout,refresh:async()=>{if(state?.mode==='cloud')setState({...await remote('state'),mode:'cloud'})}}}>{children}</C.Provider>}
