import {createSign,randomUUID} from 'node:crypto';
import {initialSchool} from '../src/content.js';
import {newUser,mutate,gradeUser} from '../src/domain.js';
import {validateAccount,changeRole} from '../src/accounts.js';
let cachedToken;
const fail=(status,message)=>Object.assign(new Error(message),{status});
const env=()=>({project:process.env.FIREBASE_PROJECT_ID,key:process.env.FIREBASE_API_KEY,email:process.env.FIREBASE_CLIENT_EMAIL,privateKey:process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g,'\n')});
async function jsonFetch(url,options={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(15000)});const j=await r.json();if(!r.ok)throw fail(r.status,r.status===409||r.status===412?'Dữ liệu đã thay đổi, vui lòng thử lại.':'Dịch vụ chưa sẵn sàng hoặc không đủ quyền.');return j}
async function token(){if(cachedToken&&cachedToken.until>Date.now())return cachedToken.value;const e=env();const b=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const now=Math.floor(Date.now()/1000);const unsigned=b({alg:'RS256',typ:'JWT'})+'.'+b({iss:e.email,scope:'https://www.googleapis.com/auth/datastore https://www.googleapis.com/auth/identitytoolkit',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});const sig=createSign('RSA-SHA256').update(unsigned).sign(e.privateKey,'base64url');const j=await jsonFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:unsigned+'.'+sig})});cachedToken={value:j.access_token,until:Date.now()+3300000};return j.access_token}
const base=()=>`https://firestore.googleapis.com/v1/projects/${env().project}/databases/(default)/documents`;
async function read(path){const r=await fetch(base()+'/'+path,{headers:{Authorization:'Bearer '+await token()},signal:AbortSignal.timeout(15000)});if(r.status===404)return null;if(!r.ok)throw fail(503,'Không đọc được dữ liệu trường học.');const j=await r.json();return {value:JSON.parse(j.fields.payload.stringValue),updateTime:j.updateTime}}
async function commit(changes){const writes=changes.map(({path,value,old})=>({update:{name:`projects/${env().project}/databases/(default)/documents/${path}`,fields:{payload:{stringValue:JSON.stringify(value)}}},currentDocument:old?{updateTime:old.updateTime}:{exists:false}}));await jsonFetch(base()+':commit',{method:'POST',headers:{Authorization:'Bearer '+await token(),'content-type':'application/json'},body:JSON.stringify({writes})})}
async function allUsers(){let result=[],next='';do{const j=await jsonFetch(base()+'/users?pageSize=100'+(next?'&pageToken='+encodeURIComponent(next):''),{headers:{Authorization:'Bearer '+await token()}});result.push(...(j.documents||[]).map(d=>JSON.parse(d.fields.payload.stringValue)));next=j.nextPageToken||''}while(next);return result}
function sanitize(s,u){if(u.role==='teacher')return s;const copy=structuredClone(s);copy.classes=copy.classes.filter(c=>c.id===u.classId).map(({code,...c})=>c);for(const key of ['exams','assignments','announcements'])copy[key]=copy[key].filter(x=>x.classId===u.classId);const publicIds=new Set(copy.lessons.map(l=>l.question?.id));copy.questions=copy.questions.filter(q=>publicIds.has(q.id));delete copy.settings.knowledge;delete copy.settings.aiModels;return copy}
function publicUser(u){const copy=structuredClone(u);for(const a of copy.attempts)if(a.status==='active')a.questions=a.questions.map(({correct,explanation,...q})=>q);return copy}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type','application/json');try{
const e=env();const configured=!!(e.project&&e.key&&e.email&&e.privateKey);if(req.method==='GET')return res.status(200).json({configured,apiKey:configured?e.key:null,aiConfigured:!!process.env.GEMINI_API_KEY});if(req.method!=='POST')return res.status(405).json({error:'Phương thức không hỗ trợ.'});if(!configured)throw fail(503,'Chưa kết nối Firebase. Em có thể dùng chế độ trải nghiệm.');
const raw=typeof req.body==='string'?JSON.parse(req.body):req.body; if(JSON.stringify(raw).length>150000)throw fail(413,'Dữ liệu gửi quá lớn.');const {action,payload:p={}}=raw||{};
const bearer=req.headers.authorization?.replace(/^Bearer /,'');if(!bearer)throw fail(401,'Cần đăng nhập.');const lookup=await jsonFetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+e.key,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idToken:bearer})});const identity=lookup.users?.[0];if(!identity)throw fail(401,'Phiên đăng nhập hết hạn.');
const admin=identity.emailVerified&&String(process.env.ADMIN_EMAIL||'').toLowerCase()===identity.email?.toLowerCase();
let [sd,ud]=await Promise.all([read('school/main'),read('users/'+identity.localId)]);let s=sd?.value||initialSchool(),u=ud?.value||newUser(identity.localId,identity.displayName||identity.email.split('@')[0]);u.isAdmin=!!admin;u.email=identity.email;u.role=admin||ud?.value.role==='teacher'?'teacher':'student';const teacher=u.role==='teacher';
if(action==='state'){if(!sd||!ud)await commit([...(!sd?[{path:'school/main',value:s,old:sd}]:[]),...(!ud?[{path:'users/'+u.id,value:u,old:ud}]:[])]);return res.status(200).json({school:sanitize(s,u),user:publicUser(u),users:teacher?await allUsers():[]})}

if(['createAccount','resetAccount','setRole'].includes(action)){
 if(!teacher)throw fail(403,'Không đủ quyền quản lý tài khoản.');
 if(action==='createAccount'){
  const value=validateAccount(u,s,{...p,id:randomUUID()});
  await jsonFetch('https://identitytoolkit.googleapis.com/v1/projects/'+e.project+'/accounts?key='+e.key,{method:'POST',headers:{Authorization:'Bearer '+await token(),'content-type':'application/json'},body:JSON.stringify({localId:value.id,email:value.email,password:p.password,displayName:value.name})});
  await commit([{path:'users/'+value.id,value,old:null}]);
 }else{
  if(!/^[a-zA-Z0-9_-]+$/.test(p.userId))throw fail(400,'Tài khoản không hợp lệ.');
  const target=await read('users/'+p.userId);if(!target)throw fail(404,'Không tìm thấy tài khoản.');
  if(action==='setRole'){const value=changeRole(u,target.value,p.role);await commit([{path:'users/'+p.userId,value,old:target}]);}
  else{if(target.value.role!=='student')throw fail(403,'Chỉ đổi mật khẩu tài khoản học sinh.');if(typeof p.password!=='string'||p.password.length<8||p.password.length>128)throw fail(400,'Mật khẩu cần 8–128 ký tự.');
   await jsonFetch('https://identitytoolkit.googleapis.com/v1/projects/'+e.project+'/accounts:update',{method:'POST',headers:{Authorization:'Bearer '+await token(),'content-type':'application/json'},body:JSON.stringify({localId:p.userId,password:p.password})});}
 }
 return res.status(200).json({school:s,user:publicUser(u),users:await allUsers()});
}

if(action==='chat'){
if(u.attempts.some(a=>a.status==='active'))throw fail(403,'Trợ lý tạm ẩn trong lúc kiểm tra.');if(typeof p.message!=='string'||!p.message.trim()||p.message.length>2000)throw fail(400,'Câu hỏi tối đa 2000 ký tự.');
const currentDay=new Date().toISOString().slice(0,10);const ai=u.aiUsage?.day===currentDay?u.aiUsage:{day:currentDay,count:0,last:0};if(ai.count>=30||Date.now()-ai.last<4000)throw fail(429,'Vui lòng chờ hoặc quay lại ngày mai (30 câu hỏi/ngày).');const key=p.personalKey||process.env.GEMINI_API_KEY;if(typeof key!=='string'||key.length<10)throw fail(503,'Giáo viên chưa cấu hình AI.');u.aiUsage={day:currentDay,count:ai.count+1,last:Date.now()};await commit([{path:'users/'+u.id,value:u,old:ud}]);
const models=(s.settings.aiModels||process.env.GEMINI_MODELS||'gemini-2.5-flash').split(',').map(x=>x.trim()).filter(x=>/^[a-zA-Z0-9.-]+$/.test(x));const context=(s.settings.knowledge||'')+'\n'+s.lessons.filter(l=>p.lessonId===l.id).map(l=>l.title+': '+l.concepts.join(' ')).join('\n');
for(const model of models){const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+model+':generateContent',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':key},signal:AbortSignal.timeout(18000),body:JSON.stringify({systemInstruction:{parts:[{text:'Bạn là trợ lý KHTN 9 theo bộ Kết nối tri thức với cuộc sống. Không bịa số trang hoặc trích dẫn SGK. Dùng tiếng Việt ngắn gọn, thân thiện, hỏi gợi mở. Không bịa số liệu; nêu rõ khi chưa chắc. Không hướng dẫn thí nghiệm nguy hiểm. Nội dung tham khảo: '+context.slice(0,30000)}]},contents:[{role:'user',parts:[{text:p.message}]}],generationConfig:{maxOutputTokens:1200}})});if(r.ok){const j=await r.json();const answer=j.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('');if(answer)return res.status(200).json({answer})}if(![429,500,502,503,504].includes(r.status))break}throw fail(503,'AI đang bận hoặc model chưa khả dụng; vui lòng thử lại.')}
if(action==='grade'){if(!teacher)throw fail(403,'Không đủ quyền.');if(!/^[a-zA-Z0-9_-]+$/.test(p.userId))throw fail(400,'Tài khoản không hợp lệ.');const target=await read('users/'+p.userId);if(!target)throw fail(404,'Không tìm thấy học sinh.');const value=gradeUser(u,target.value,p);await commit([{path:'users/'+p.userId,value,old:target}]);return res.status(200).json({school:s,user:u,users:await allUsers()})}
const next=mutate(s,u,action,p);await commit([{path:'users/'+u.id,value:next.user,old:ud},...(JSON.stringify(s)!==JSON.stringify(next.school)?[{path:'school/main',value:next.school,old:sd}]:[])]);return res.status(200).json({school:sanitize(next.school,next.user),user:publicUser(next.user),users:teacher?await allUsers():[]});
}catch(error){res.status(error.status||400).json({error:error.status?error.message:(error.message?.includes('PEM')?'Cấu hình kết nối máy chủ chưa hợp lệ.':error.message||'Không thể hoàn thành thao tác.')})}}
